name: "Build ios ipa"
on:
  workflow_dispatch:

jobs:
  do_tests:
    name: Flutter Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            assets
            lib
            test
            scripts
      - uses: subosito/flutter-action@v2
        with:
          cache: true
          
      - name: Download dependencies
        run: flutter pub get
      - name: Run tests
        run: flutter test
  gen_icons:
    name: Generate icons & commit/push them
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check latest commit to assets
        id: assets
        # This job should not run when the latest commit to assets is older than 1 day
        # This is to reduce unnecessary running minutes
        run: |
          COMMITS=$(curl -s "https://api.github.com/repos/${{ github.repository }}/commits?path=assets&page=1&per_page=1")
          DAYS=$(echo $COMMITS | jq -r "((now - (.[0].commit.committer.date | fromdateiso8601) )  / (60*60*24)  | trunc)")
          echo "days=$DAYS" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v4
        if: steps.assets.output.days == 0
        with:
          ref: main
      - uses: subosito/flutter-action@v2
        if: steps.assets.output.days == 0
        with:
          cache: true
      - name: Download dependencies
        run: flutter pub get
      - name: Generate flutter launcher icons
        if: steps.assets.output.days == 0
        run: flutter pub run flutter_launcher_icons
      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v4
        if: steps.assets.output.days == 0
        with:
          commit_message: Generated icon files
          file_pattern: '*.xml *.json *.png'
  build_ios:
    name: Build iOS ipa
    needs: [ do_tests, gen_icons ]
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
        #with:
        #  sparse-checkout: |
        #    assets
        #    lib
        #    scripts
        #    ios
      - uses: subosito/flutter-action@v2
        with:
          cache: true
          
      - name: Gathering dependencies
        run: flutter pub get
      - name: Build ios xcarchive
        run: flutter build ipa --release --no-codesign
      - name: Package xcarchive to ipa
        run: |
          brew install ldid
          chmod +x ${PWD}/scripts/package_ipa.sh 
          ${PWD}/scripts/package_ipa.sh ${PWD}/build/ios/archive/Runner.xcarchive .
          ls
      - name: Get current date
        id: date
        run: echo "date={$(date +'%Y-%m-%d')}" >> $GITHUB_ENV
      - name: Push artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: musify-${{ env.date }}.ipa
          path: ./musify.ipa

